In [1]:
import tensorflow as tf
import imageio
import os
from PIL import Image
import pandas as pd
import numpy as np

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images,train_labels),(test_images, test_labels) = fashion_mnist.load_data()

In [4]:
N = tr.shape[0]

In [2]:
tr = pd.read_csv('Ytr.txt')
te = pd.read_csv('pred.txt')

In [18]:
te

id  score
0      618      0
1      620      0
2      623      0
3      625      0
4      629      0
...    ...    ...
2509  6141      0
2510  6143      0
2511  6144      0
2512  6146      0
2513  6147      0

[2514 rows x 2 columns]

In [10]:
D = 28 # Dimension of images after resizing
Xtr = np.zeros([N,D,D])

In [4]:
ii = 0
path = 'images/%05d.png' %ii
        
pic = imageio.imread(path)

pic.shape

(256, 256, 3)

In [12]:
found = list()
for ii in range(N):
    if ii % 100 == 0:
        print('%d / %d' % (ii, N))

    path = 'images/%05d.png' %ii
        
    pic = imageio.imread(path)
    pic = Image.fromarray(pic).resize((D,D)) # NOTE : this can be improved.
    pic = np.mean(pic,axis = 2) # NOTE: this can be improved
    pic = np.array(pic)
    # print(pic.shape)
    Xtr[ii,:,:] = pic

0 / 3634
100 / 3634
200 / 3634
300 / 3634
400 / 3634
500 / 3634
600 / 3634
700 / 3634
800 / 3634
900 / 3634
1000 / 3634
1100 / 3634
1200 / 3634
1300 / 3634
1400 / 3634
1500 / 3634
1600 / 3634
1700 / 3634
1800 / 3634
1900 / 3634
2000 / 3634
2100 / 3634
2200 / 3634
2300 / 3634
2400 / 3634
2500 / 3634
2600 / 3634
2700 / 3634
2800 / 3634
2900 / 3634
3000 / 3634
3100 / 3634
3200 / 3634
3300 / 3634
3400 / 3634
3500 / 3634
3600 / 3634


In [30]:
Xtr2 = Xtr/255

In [31]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape = (D,D)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(2) # output neuron for number of classes
])

In [32]:
model.compile(optimizer = 'adam', 
              loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics = ['accuracy'])

In [80]:
model.fit(Xtr2, np.array(tr['label']), epochs = 10) # guessing 0 have higher chance than accuracy

# DNN with 28x28 & N = 1000 yields 0.64
# DNN with 28x28 & N = tr.shape[0] yields 0.53
# Continue?
# DNN with 28x28 & N = tr.shape[0] , epochs = 1000 yields
# DNN with 50x50 & N = tr.shape[0] epochs = 1000 yields 

# or
# Look at something simpler - how much orange in image?
# or
# use cnn (convolutional) https://blog.tensorflow.org/2018/04/fashion-mnist-with-tfkeras.html

Epoch 1/10
114/114 [==============================] - 0s 4ms/step - loss: 0.6633 - accuracy: 0.6189
Epoch 2/10
114/114 [==============================] - 0s 3ms/step - loss: 0.6564 - accuracy: 0.6189
Epoch 3/10
114/114 [==============================] - 0s 4ms/step - loss: 0.6545 - accuracy: 0.6197
Epoch 4/10
114/114 [==============================] - 0s 3ms/step - loss: 0.6566 - accuracy: 0.6186
Epoch 5/10
114/114 [==============================] - 0s 3ms/step - loss: 0.6562 - accuracy: 0.6150
Epoch 6/10
114/114 [==============================] - 0s 2ms/step - loss: 0.6526 - accuracy: 0.6216
Epoch 7/10
114/114 [==============================] - 0s 3ms/step - loss: 0.6516 - accuracy: 0.6255
Epoch 8/10
114/114 [==============================] - 0s 2ms/step - loss: 0.6537 - accuracy: 0.6170
Epoch 9/10
114/114 [==============================] - 0s 2ms/step - loss: 0.6506 - accuracy: 0.6214
Epoch 10/10
114/114 [==============================] - 0s 3ms/step - loss: 0.6548 - accuracy: 0.6236

In [23]:
te['id']

0        618
1        620
2        623
3        625
4        629
        ... 
2509    6141
2510    6143
2511    6144
2512    6146
2513    6147
Name: id, Length: 2514, dtype: int64

In [24]:
D = 28 # Dimension of images after resizing
N = te.shape[0]
Xte = np.zeros([N,D,D])
found = list()
for ii in range(N):
    if ii % 100 == 0:
        print('%d / %d' % (ii, N))
    teId = te['id'][ii]
    path = 'images/%05d.png' %teId
        
    pic = imageio.imread(path)
    pic = Image.fromarray(pic).resize((D,D)) # NOTE : this can be improved.
    pic = np.mean(pic,axis = 2) # NOTE: this can be improved
    pic = np.array(pic)
    # print(pic.shape)
    Xte[ii,:,:] = pic

0 / 2514
100 / 2514
200 / 2514
300 / 2514
400 / 2514
500 / 2514
600 / 2514
700 / 2514
800 / 2514
900 / 2514
1000 / 2514
1100 / 2514
1200 / 2514
1300 / 2514
1400 / 2514
1500 / 2514
1600 / 2514
1700 / 2514
1800 / 2514
1900 / 2514
2000 / 2514
2100 / 2514
2200 / 2514
2300 / 2514
2400 / 2514
2500 / 2514


In [34]:
Xte2 = Xte/255

In [81]:
preds = model.predict(Xte2)

In [82]:
preds

array([[-0.13217375, -0.23582153],
       [ 0.31179634, -0.33921182],
       [ 0.25503376, -0.3952964 ],
       ...,
       [ 0.07474652, -0.3258608 ],
       [ 0.02470782, -0.2948069 ],
       [ 0.39199814, -0.40421438]], dtype=float32)

In [68]:
pred = tf.nn.sigmoid(preds)
pred = tf.where(pred<0.5, 0 , 1)

array([[1, 1],
       [1, 0],
       [1, 0],
       ...,
       [1, 0],
       [1, 1],
       [1, 0]])

In [54]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(Xtr2,tr['label'],test_size = 0.2, random_state = 42)

In [83]:
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test,y_test))

Epoch 1/5
91/91 [==============================] - 0s 5ms/step - loss: 0.6500 - accuracy: 0.6202 - val_loss: 0.6632 - val_accuracy: 0.5915
Epoch 2/5
91/91 [==============================] - 0s 4ms/step - loss: 0.6537 - accuracy: 0.6175 - val_loss: 0.6538 - val_accuracy: 0.6190
Epoch 3/5
91/91 [==============================] - 0s 4ms/step - loss: 0.6530 - accuracy: 0.6151 - val_loss: 0.6688 - val_accuracy: 0.6245
Epoch 4/5
91/91 [==============================] - 0s 4ms/step - loss: 0.6513 - accuracy: 0.6271 - val_loss: 0.6632 - val_accuracy: 0.5846
Epoch 5/5
91/91 [==============================] - 0s 3ms/step - loss: 0.6493 - accuracy: 0.6237 - val_loss: 0.6641 - val_accuracy: 0.6011


1289    0
120     0
839     1
1537    0
2890    0
       ..
343     0
1652    0
1592    0
678     0
1831    0
Name: label, Length: 727, dtype: int64

In [75]:
model.predict(X_test)

array([[-0.0930413 , -0.45244193],
       [ 0.0761469 , -0.3376736 ],
       [ 0.01296997, -0.45653886],
       ...,
       [-0.00528729, -0.4273917 ],
       [ 0.11757076, -0.40412998],
       [-0.41486728, -0.36487132]], dtype=float32)

In [90]:
def read_image(N,D,X):
    Xt = np.zeros([N,D,D])
    #found = list()
    for ii in range(N):
        if ii % 100 == 0:
            print('%d / %d' % (ii, N))
        teId = X['id'][ii]
        path = 'images/%05d.png' %teId
        
        pic = imageio.imread(path)
        pic = Image.fromarray(pic).resize((D,D)) # NOTE : this can be improved.
        pic = np.mean(pic,axis = 2) # NOTE: this can be improved
        pic = np.array(pic)
        # print(pic.shape)
        Xt[ii,:,:] = pic
    Xt = Xt/255
    return Xt

In [91]:
Xtr_1 = read_image(tr.shape[0],200,tr)

0 / 3634
100 / 3634
200 / 3634
300 / 3634
400 / 3634
500 / 3634
600 / 3634
700 / 3634
800 / 3634
900 / 3634
1000 / 3634
1100 / 3634
1200 / 3634
1300 / 3634
1400 / 3634
1500 / 3634
1600 / 3634
1700 / 3634
1800 / 3634
1900 / 3634
2000 / 3634
2100 / 3634
2200 / 3634
2300 / 3634
2400 / 3634
2500 / 3634
2600 / 3634
2700 / 3634
2800 / 3634
2900 / 3634
3000 / 3634
3100 / 3634
3200 / 3634
3300 / 3634
3400 / 3634
3500 / 3634
3600 / 3634


In [92]:
Xtr_1

array([[[0.81568627, 0.8       , 0.78823529, ..., 0.25490196,
         0.26666667, 0.27843137],
        [0.85098039, 0.84705882, 0.81568627, ..., 0.23529412,
         0.22352941, 0.27843137],
        [0.77254902, 0.81960784, 0.80392157, ..., 0.27843137,
         0.25490196, 0.28627451],
        ...,
        [0.28627451, 0.2745098 , 0.26666667, ..., 0.25490196,
         0.27843137, 0.25882353],
        [0.27058824, 0.25098039, 0.26666667, ..., 0.27843137,
         0.30588235, 0.25882353],
        [0.28235294, 0.2745098 , 0.24705882, ..., 0.24705882,
         0.31372549, 0.24313725]],

       [[0.41176471, 0.33594771, 0.32026144, ..., 0.45359477,
         0.46013072, 0.46797386],
        [0.45751634, 0.32418301, 0.25751634, ..., 0.44052288,
         0.44836601, 0.45620915],
        [0.48104575, 0.42222222, 0.37385621, ..., 0.44444444,
         0.45228758, 0.46013072],
        ...,
        [0.37647059, 0.36470588, 0.36078431, ..., 0.30326797,
         0.39738562, 0.25228758],
        [0.3

In [110]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,(3,3), activation = 'relu', input_shape = (200,200,1)),
    tf.keras.layers.MaxPool2D(2,2),
    
    tf.keras.layers.Conv2D(32,(3,3), activation = 'relu'),
    tf.keras.layers.MaxPool2D(2,2),
    
    tf.keras.layers.Conv2D(64,(3,3), activation = 'relu'),
    tf.keras.layers.MaxPool2D(2,2),
    
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'sigmoid') # output neuron for number of classes
])

In [111]:
model.compile(loss = 'binary_crossentropy',
             optimizer = tf.keras.optimizers.RMSprop(learning_rate = 0.001),
              metrics = ['accuracy'])

In [105]:
Xtr_2 = Xtr_1.reshape(-1,200,200,1)

In [112]:
model.fit(Xtr_2,np.array(tr['label']), epochs = 30)

Epoch 1/30
114/114 [==============================] - 11s 53ms/step - loss: 0.8331 - accuracy: 0.6021
Epoch 2/30
114/114 [==============================] - 6s 49ms/step - loss: 0.6842 - accuracy: 0.6010
Epoch 3/30
114/114 [==============================] - 6s 51ms/step - loss: 0.6656 - accuracy: 0.6156
Epoch 4/30
114/114 [==============================] - 6s 52ms/step - loss: 0.6500 - accuracy: 0.6249
Epoch 5/30
114/114 [==============================] - 6s 51ms/step - loss: 0.6343 - accuracy: 0.6511 0s - loss: 0.638
Epoch 6/30
114/114 [==============================] - 6s 51ms/step - loss: 0.6023 - accuracy: 0.6835
Epoch 7/30
114/114 [==============================] - 6s 51ms/step - loss: 0.5653 - accuracy: 0.7133
Epoch 8/30
114/114 [==============================] - 6s 51ms/step - loss: 0.5135 - accuracy: 0.7427
Epoch 9/30
114/114 [==============================] - 6s 51ms/step - loss: 0.4590 - accuracy: 0.7870
Epoch 10/30
114/114 [==============================] - 6s 52ms/step - los

In [109]:
Xtr_2.shape

(3634, 200, 200, 1)

In [118]:
X_train, X_test, y_train, y_test = train_test_split(Xtr_2,np.array(tr['label']),test_size = 0.2, random_state = 42)

In [119]:
model.fit(X_train,y_train, epochs = 40, validation_data = (X_test,y_test))

Epoch 1/40
91/91 [==============================] - 6s 64ms/step - loss: 0.0436 - accuracy: 0.9859 - val_loss: 0.0266 - val_accuracy: 0.9945
Epoch 2/40
91/91 [==============================] - 5s 54ms/step - loss: 0.0512 - accuracy: 0.9835 - val_loss: 0.0179 - val_accuracy: 0.9959
Epoch 3/40
91/91 [==============================] - 5s 54ms/step - loss: 0.0440 - accuracy: 0.9880 - val_loss: 0.0206 - val_accuracy: 0.9959
Epoch 4/40
91/91 [==============================] - 5s 54ms/step - loss: 0.0546 - accuracy: 0.9835 - val_loss: 0.0624 - val_accuracy: 0.9945
Epoch 5/40
91/91 [==============================] - 5s 56ms/step - loss: 0.0345 - accuracy: 0.9900 - val_loss: 0.0700 - val_accuracy: 0.9780
Epoch 6/40
91/91 [==============================] - 5s 56ms/step - loss: 0.0748 - accuracy: 0.9804 - val_loss: 0.0349 - val_accuracy: 0.9931
Epoch 7/40
91/91 [==============================] - 6s 62ms/step - loss: 0.0496 - accuracy: 0.9849 - val_loss: 0.0395 - val_accuracy: 0.9904
Epoch 8/40
91

In [113]:
Xte_1 = read_image(te.shape[0],200,te)
Xte_2 = Xte_1.reshape(-1,200,200,1)

0 / 2514
100 / 2514
200 / 2514
300 / 2514
400 / 2514
500 / 2514
600 / 2514
700 / 2514
800 / 2514
900 / 2514
1000 / 2514
1100 / 2514
1200 / 2514
1300 / 2514
1400 / 2514
1500 / 2514
1600 / 2514
1700 / 2514
1800 / 2514
1900 / 2514
2000 / 2514
2100 / 2514
2200 / 2514
2300 / 2514
2400 / 2514
2500 / 2514


In [114]:
pred = model.predict(Xte_2)

In [117]:
np.round(pred)

array([[1.],
       [0.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]], dtype=float32)

In [122]:
te1 = te.copy()

In [123]:
te1['score'] = pred

In [125]:
te1.to_csv('pred1.csv',index = False)

In [126]:
te2 = te.copy()

In [127]:
te2['score'] = np.round(pred)

In [129]:
te2.to_csv('pred2.csv',index = False)

In [131]:
te2['score'] = 0
te2.to_csv('pred3.csv',index = False)
te2['score'] = 1
te2.to_csv('pred4.csv',index = False)